Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
January 04, 2023 - 11:00:47
Django version 4.1.5, using settings 'todoApp.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Invalid HTTP_HOST header: '54.250.159.19:8000'. You may need to add '54.250.159.19' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.10/dist-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.250.159.19:8000'. You may need to add '54.250.159.19' to ALLOWED_HOSTS.
Bad Request: /
[04/Jan/2023 11:01:07] "GET / HTTP/1.1" 400 61225
Invalid HTTP_HOST header: '54.250.159.19:8000'. You may need to add '54.250.159.19' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.10/dist-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.250.159.19:8000'. You may need to add '54.250.159.19' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[04/Jan/2023 11:01:08] "GET /favicon.ico HTTP/1.1" 400 61208
/root/projects/django-todo/todoApp/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
January 04, 2023 - 11:02:11
Django version 4.1.5, using settings 'todoApp.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[04/Jan/2023 11:02:16] "GET / HTTP/1.1" 302 0
[04/Jan/2023 11:02:16] "GET /todos HTTP/1.1" 301 0
[04/Jan/2023 11:02:17] "GET /todos/ HTTP/1.1" 200 3515
[04/Jan/2023 11:02:17] "GET /static/css/style.css HTTP/1.1" 200 225
